/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzaria.models.cliente.view;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import pizzaria.models.cliente.Cliente;
import pizzaria.models.cliente.ClienteController;
import pizzaria.models.cliente.ClienteDao;

/**
 *
 * @author chris
 */
public class ClienteFormView extends javax.swing.JFrame {

        private final ClienteDao clienteDao;
        private Cliente cliente = null;
        private final ClienteController clienteController;

        /**
         * Creates new form ClienteFormView
         */
        public ClienteFormView(ClienteDao clienteDao, ClienteController clienteController) {
                this.clienteDao = clienteDao;
                this.clienteController = clienteController;
                initComponents();
        }

        public ClienteFormView(ClienteDao clienteDao, ClienteController clienteController, Cliente cliente) {
                this.clienteDao = clienteDao;
                this.clienteController = clienteController;
                this.cliente = cliente;
                this.setVisible(true);
                initComponents();
                setClienteValues(cliente);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btSalvar = new javax.swing.JButton();
                btCancelar = new javax.swing.JButton();
                jLabel4 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                endereco = new javax.swing.JTextField();
                jLabel1 = new javax.swing.JLabel();
                telefone = new javax.swing.JTextField();
                sobrenome = new javax.swing.JTextField();
                nome = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btSalvar.setBackground(new java.awt.Color(153, 255, 153));
                btSalvar.setText("Salvar");
                btSalvar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btSalvarActionPerformed(evt);
                        }
                });

                btCancelar.setBackground(new java.awt.Color(255, 102, 102));
                btCancelar.setText("Cancelar");
                btCancelar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btCancelarActionPerformed(evt);
                        }
                });

                jLabel4.setText("Endereço:");

                jLabel3.setText("Telefone:");

                jLabel2.setText("Sobrenome:");

                jLabel1.setText("Nome:");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btCancelar)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(btSalvar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                79,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addGap(46, 46, 46)
                                                                                                                .addGroup(layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addComponent(jLabel3)
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addGroup(layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(nome,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                300,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(telefone,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                300,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(sobrenome,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                300,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                .addComponent(endereco,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                300,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap(54, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(50, 50, 50)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(nome,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(sobrenome,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jLabel3)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(telefone,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(endereco,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(35, 35, 35)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btCancelar)
                                                                                .addComponent(btSalvar))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void setClienteValues(Cliente cliente) {
                if (cliente != null) {
                        this.nome.setText(cliente.getNome());
                        this.sobrenome.setText(cliente.getSobrenome());
                        this.telefone.setText(cliente.getTelefone());
                        this.endereco.setText(cliente.getEndereco());
                        this.cliente = cliente;
                }
        }

        private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btSalvarActionPerformed

                JFrame frame = new JFrame("frame");
                String[] listaDeCampos = { "nome", "sobrenome", "telefone", "endereco" };
                if (stringEmpty(frame, listaDeCampos, nome.getText(), sobrenome.getText(), telefone.getText(),
                                endereco.getText())) {
                        return;
                }
                if (this.cliente == null) {
                        this.clienteController.addCliente(nome.getText(), sobrenome.getText(), telefone.getText(),
                                        endereco.getText());
                } else {
                        this.clienteController.updateCliente(cliente.getId(), nome.getText(), sobrenome.getText(),
                                        telefone.getText(),
                                        endereco.getText());
                }
                this.dispose();
        }

        // GEN-LAST:event_btSalvarActionPerformed

        private boolean stringEmpty(JFrame frame, String[] campos, String... strings) {
                Boolean value = false;
                int x = 0;
                for (String string : strings) {
                        if (string.isEmpty()) {
                                JOptionPane.showMessageDialog(frame, "Por favor, preencha o campo " + campos[x] + ".");
                                value = true;
                        }
                        x++;
                }
                return value;
        }

        private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btCancelarActionPerformed
                this.dispose();
        }// GEN-LAST:event_btCancelarActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ClienteFormView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ClienteFormView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ClienteFormView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ClienteFormView.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                // new ClienteFormView().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btCancelar;
        private javax.swing.JButton btSalvar;
        private javax.swing.JTextField endereco;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JTextField nome;
        private javax.swing.JTextField sobrenome;
        private javax.swing.JTextField telefone;
        // End of variables declaration//GEN-END:variables
}
